command = [
  "env",
  "PATH=/opt/homebrew/opt/openjdk/bin:/Users/ssyram/.cargo/bin:/usr/bin:/bin",
  "RUSTUP_TOOLCHAIN=nightly-2023-08-15-x86_64-apple-darwin",
  "arch", "-x86_64",
  "/tmp/ts-tools-install/prusti/cargo-prusti"
]
timeout_secs = 900
