command      = ["${TS_CHARON_BIN}", "cargo", "--monomorphize", "--abort-on-error", "--print-llbc", "--", "--lib", "--target", "aarch64-apple-darwin"]
timeout_secs = 600
version_command = ["${TS_CHARON_BIN}", "version"]
