/// NaN propagation through arithmetic chains and the is_nan / is_finite / is_infinite
/// classification predicates; separately tests NaN generated from 0.0/0.0 vs f64::NAN literal.
/// Tools that model NaN as a single abstract value vs. preserving payload bits will diverge here.
pub fn float_nan_prop() {
    // NaN generated by operation
    let zero: f64 = 0.0_f64;
    let op_nan: f64 = zero / zero; // 0/0 = NaN per IEEE 754

    // propagation: any arithmetic with NaN stays NaN
    let _p1: f64 = op_nan + 1.0;
    let _p2: f64 = op_nan * 2.0;
    let _p3: f64 = op_nan - op_nan;  // NaN - NaN = NaN (not 0)
    let _p4: f64 = op_nan.abs();     // NaN.abs() = NaN

    // classification predicates
    let _is_nan: bool = op_nan.is_nan();           // true
    let _is_fin: bool = op_nan.is_finite();        // false
    let _is_inf: bool = op_nan.is_infinite();      // false

    let inf: f64 = f64::INFINITY;
    let _inf_not_nan: bool = inf.is_nan();         // false
    let _inf_is_inf: bool = inf.is_infinite();     // true
    let _inf_not_fin: bool = inf.is_finite();      // false

    let normal: f64 = 1.0_f64;
    let _norm_is_fin: bool = normal.is_finite();   // true
    let _norm_is_normal: bool = normal.is_normal(); // true

    // subnormal is finite but not normal
    let sub: f64 = 5e-324_f64; // smallest positive subnormal
    let _sub_is_fin: bool = sub.is_finite();   // true
    let _sub_not_norm: bool = sub.is_normal(); // false
}
